{{- range $node := .Values.indy.nodes }}
---
apiVersion: v1
kind: Secret
metadata:
  name: indy-seed-{{ $node.alias }}
  labels:
    {{- include "indy.labels" $ | nindent 4 }}
    node: {{ $node.alias }}
type: Opaque
data:
  seed: {{ $node.seed | b64enc | quote }}
{{- end }}
