version: "3.8"

services:
  indy-node:
    image: ${IMAGE}
    container_name: indy_node
    ports:
      - "${INDY_NODE_PORT}:${INDY_NODE_PORT}"
      - "${INDY_CLIENT_PORT}:${INDY_CLIENT_PORT}"

    volumes:
      - ./etc_indy:/etc/indy
      - ./lib_indy:/var/lib/indy
    env_file:
      - .env
      - .node.env
    restart: always
