name: Ubuntu 18 Build

on: [push]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: build and push ubuntu18 base
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: build/Dockerfile.base.ubuntu18
          path: build
          registry: ghcr.io
          repository: idunion/indy-node-container/base
          tags: ubuntu18

      - name: build and push indy node based on ubuntu18
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: build/Dockerfile
          path: build
          registry: ghcr.io
          repository: idunion/indy-node-container/indy_node
          tags: ubuntu18
          build_args: BASE=ghcr.io/idunion/indy-node-container/base:ubuntu18
