name: Buster Build

on: [push]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: build and push buster base
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: build/Dockerfile.base.buster
          path: build
          registry: docker.pkg.github.com
          repository: idunion/docker-container-wg/base
          tags: buster

      - name: build and push indy node based on buster
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: build/Dockerfile
          path: build
          registry: docker.pkg.github.com
          repository: idunion/docker-container-wg/indy_node
          tags: buster, latest
          build_args: BASE=docker.pkg.github.com/idunion/docker-container-wg/base:buster
