name: Ubuntu 18 Build

on:
  push:
    branches:
        - main
  pull_request:
    branches: [ main ]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push ubuntu18 base
        uses: docker/build-push-action@v2
        with:
          file: build/Dockerfile.base.ubuntu18
          context: ./build
          tags: idunion/indy-node-container/base:ubuntu18

      - name: build and push indy node based on ubuntu18
        uses: docker/build-push-action@v2
        with:
          file: build/Dockerfile
          context: ./build
          tags: idunion/indy-node-container/indy_node:ubuntu18
          build-args: BASE=ghcr.io/idunion/indy-node-container/base:ubuntu18
