name: Buster Build

on: [push]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push buster base
        uses: docker/build-push-action@v2
        with:
          file: build/Dockerfile.base.buster
          context: ./build
          tags: idunion/indy-node-container/base:buster

      - name: build and push indy node based on buster
        uses: docker/build-push-action@v2
        with:
          file: build/Dockerfile
          context: ./build
          tags: idunion/indy-node-container/indy_node:buster,idunion/indy-node-container/indy_node:latest
          build-args: BASE=ghcr.io/idunion/indy-node-container/base:buster
