name: Test ledger

on:
  workflow_dispatch:

jobs:
  test:
    name: Test ledger with docker-compose
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Start 4 nodes and the ledger browser
        run: |
          cd test
          ./init-test-network.sh
          docker-compose up -d

      - name: Get Ledger State
        id: ledger
        run: |
          echo "Waiting 30 seconds for the ledger browser to start ..."
          sleep 30
          curl -s --retry 5 --retry-delay 5 --max-time 10 http://localhost:9000/status?validators=1 > ledger_state.json
          SYNC_STATE_N1=$(jq '.validators[0].Node_info.Catchup_status.Ledger_statuses[] | . == "synced"' ledger_state.json | sort -u)
          SYNC_STATE_N2=$(jq '.validators[1].Node_info.Catchup_status.Ledger_statuses[] | . == "synced"' ledger_state.json | sort -u)
          SYNC_STATE_N3=$(jq '.validators[2].Node_info.Catchup_status.Ledger_statuses[] | . == "synced"' ledger_state.json | sort -u)
          SYNC_STATE_N4=$(jq '.validators[3].Node_info.Catchup_status.Ledger_statuses[] | . == "synced"' ledger_state.json | sort -u)
          echo "Node 1 (synced=$SYNC_STATE_N1): $(jq '.validators[0].Node_info.Catchup_status.Ledger_statuses' ledger_state.json)"
          echo "Node 2 (synced=$SYNC_STATE_N2): $(jq '.validators[1].Node_info.Catchup_status.Ledger_statuses' ledger_state.json)"
          echo "Node 3 (synced=$SYNC_STATE_N3): $(jq '.validators[2].Node_info.Catchup_status.Ledger_statuses' ledger_state.json)"
          echo "Node 4 (synced=$SYNC_STATE_N4): $(jq '.validators[3].Node_info.Catchup_status.Ledger_statuses' ledger_state.json)"
          echo "::set-output name=n1_synced::$SYNC_STATE_N1"
          echo "::set-output name=n2_synced::$SYNC_STATE_N2"
          echo "::set-output name=n3_synced::$SYNC_STATE_N3"
          echo "::set-output name=n4_synced::$SYNC_STATE_N4"

      - name: Fail if ledger is not in sync
        if: ${{ steps.ledger.outputs.n1_synced != 'true' ||  steps.ledger.outputs.n2_synced != 'true' ||  steps.ledger.outputs.n3_synced != 'true' ||  steps.ledger.outputs.n4_synced != 'true' }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Not all nodes are in sync!')
