name: build

on:
  push:
    # branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    # branches: [ main ]
  schedule:
    # run every day at 22:44
    - cron: '44 22 * * *'

jobs:
  build:
    name: Trivy Analysis
    runs-on: "ubuntu-18.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/idunion/indy-node-container/indy_node:latest'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
