name: Trivy Analysis

on:
  schedule:
    # run every Wednesday at 23:40
    - cron: '40 23 * * 3'
  workflow_dispatch:


jobs:

  workflow_setup:
    name: Setup variables 
    runs-on: ubuntu-latest
    outputs:
      repo_owner: ${{ steps.repo_owner.outputs.lowercase }}
      os_matrix: "{\"os_version\":[\"bullseye\",\"buster\",\"ubuntu16\",\"ubuntu18\"]}"
    steps:
      - name: Lowercase repo owner
        id: repo_owner
        run: echo "::set-output name=lowercase::$(echo ${{ github.repository_owner }} | tr \"[:upper:]\" \"[:lower:]\")"
        shell: bash

  trivy_analysis:
    name: Trivy Analysis
    runs-on: ubuntu-latest
    needs: workflow_setup
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.workflow_setup.outputs.os_matrix) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set file name
        id: file
        run: echo "::set-output name=fullname::$(echo trivy-indy-node-${{ matrix.os_version }}.sarif)"
        shell: bash

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Trivy on indy_node:${{ matrix.os_version }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ needs.workflow_setup.outputs.repo_owner }}/indy-node-container/indy_node:latest-${{ matrix.os_version }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: '${{ steps.file.outputs.fullname }}'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
      
      - name: Patch tool name for ${{ matrix.os_version }} scan
        run: |
          sed -i 's/"name": "Trivy",/"name": "Trivy-${{ matrix.os_version }}",/g' ${{ steps.file.outputs.fullname }}

      - name: Safe ${{ steps.file.outputs.fullname }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.file.outputs.fullname }}
          path: ${{ steps.file.outputs.fullname }}
          retention-days: 8

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: '${{ steps.file.outputs.fullname }}'

